(()=>{const section=document.getElementById('reel-vibes');if(!section)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async body=>{const r=await fetch('/api/reels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Something went wrong.');return d};
section.innerHTML=`<div class="real-vibes-head"><div><div class="eyebrow">ORIGINAL SHORT-FORM VIDEO · HUBCORE VIBES</div><h2>Meet <span>Reel Vibes.</span></h2></div><p>Watch original drops, share your own reel, and join the conversation. Vertical, social and built for the HubCore community.</p></div>
<div class="reel-composer glass-panel"><button class="btn primary" id="openReelComposer" type="button">＋ Post your reel</button><span>Share an HTTPS link to a video you own or have permission to publish.</span><form id="reelForm" hidden><div class="reel-fields"><input name="author" maxlength="80" required placeholder="Creator name"><input name="handle" maxlength="80" placeholder="@username"><input name="title" maxlength="120" required placeholder="Reel title"><input name="videoUrl" type="url" required placeholder="https://… direct MP4/WebM or hosted reel link"></div><textarea name="caption" maxlength="800" rows="3" placeholder="Caption…"></textarea><div class="reel-form-actions"><button class="btn primary" type="submit">Publish reel</button><button class="btn ghost" id="cancelReel" type="button">Cancel</button><span id="reelFormStatus" role="status"></span></div></form></div>
<div class="real-vibes-shell"><div class="real-vibes-track" id="realVibesTrack" aria-label="Reel Vibes feed"></div><div class="real-vibes-nav"><button id="realVibesPrev" type="button" aria-label="Previous Reel">←</button><button id="realVibesNext" type="button" aria-label="Next Reel">→</button></div></div>
<p class="real-vibes-note">Swipe to explore · Tap a reel to play · Comments, likes and shares are live.</p>`;
const track=section.querySelector('#realVibesTrack'),status=section.querySelector('#reelFormStatus');
function visual(r){if(r.videoUrl&&/\.(mp4|webm|mov)(\?|$)/i.test(r.videoUrl))return `<video muted loop playsinline preload="metadata" src="${esc(r.videoUrl)}"></video>`;if(r.videoUrl)return `<a class="reel-linked" href="${esc(r.videoUrl)}" target="_blank" rel="noopener"><span>OPEN CREATOR REEL</span><small>Hosted video ↗</small></a>`;return `<div class="reel-original reel-${esc(r.theme)}"><div class="reel-scene reel-scene-a"></div><div class="reel-scene reel-scene-b"></div><div class="reel-scene reel-scene-c"></div><strong>${r.theme==='hubcore'?'ONE UNIVERSE.<br>ENDLESS CONNECTIONS.':r.theme==='food'?'WAIT FOR<br>THE REVEAL':'POV: EVERYTHING<br>FINALLY CONNECTS'}</strong></div>`}
function card(r){return `<article class="real-vibe-card" data-id="${esc(r.id)}">${visual(r)}<div class="real-vibe-progress"><i></i></div><div class="real-vibe-overlay"><span>${r.featured?'FEATURED ORIGINAL':'COMMUNITY REEL'}</span><h3>${esc(r.title)}</h3><p>${esc(r.caption)}</p><small>${esc(r.author)} ${esc(r.handle)}</small></div><div class="reel-social"><button data-like type="button" aria-label="Like">♥ <b>${r.likes}</b></button><button data-comments type="button" aria-label="Comments">● <b>${r.comments.length}</b></button><button data-share type="button" aria-label="Share">↗ <b>${r.shares}</b></button></div><div class="reel-comments" hidden><div class="reel-comment-list">${r.comments.map(c=>`<p><b>${esc(c.author)}</b> ${esc(c.text)}</p>`).join('')||'<p class="empty">Start the conversation.</p>'}</div><form data-comment-form><input name="author" maxlength="80" required placeholder="Your name"><input name="text" maxlength="1000" required placeholder="Write a comment…"><button type="submit">Post</button></form></div></article>`}
async function load(){try{const r=await fetch('/api/reels',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);track.innerHTML=d.reels.map(card).join('');bind();}catch(e){track.innerHTML=`<div class="reel-error">Reel Vibes could not load. Please try again shortly.</div>`}}
function bind(){track.querySelectorAll('.real-vibe-card').forEach(card=>{const id=card.dataset.id,video=card.querySelector('video'),like=card.querySelector('[data-like]'),share=card.querySelector('[data-share]'),comments=card.querySelector('[data-comments]'),panel=card.querySelector('.reel-comments');
video?.addEventListener('click',()=>video.paused?video.play().catch(()=>{}):video.pause());
like.onclick=async()=>{if(localStorage.getItem('hubcore-liked-'+id))return;try{const d=await api({action:'like',reelId:id});like.querySelector('b').textContent=d.total;localStorage.setItem('hubcore-liked-'+id,'1');like.classList.add('active')}catch{}};
comments.onclick=()=>{panel.hidden=!panel.hidden};
share.onclick=async()=>{const url=location.origin+location.pathname+'#reel-'+id;try{if(navigator.share)await navigator.share({title:'Reel Vibes',text:card.querySelector('h3').textContent,url});else await navigator.clipboard.writeText(url);const d=await api({action:'share',reelId:id});share.querySelector('b').textContent=d.total}catch{}};
card.querySelector('[data-comment-form]').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await api({action:'comment',reelId:id,author:fd.get('author'),text:fd.get('text')});await load()}catch(err){alert(err.message)}}})}
const form=section.querySelector('#reelForm');section.querySelector('#openReelComposer').onclick=()=>{form.hidden=false;form.querySelector('input').focus()};section.querySelector('#cancelReel').onclick=()=>{form.hidden=true};
form.onsubmit=async e=>{e.preventDefault();status.textContent='Publishing…';const fd=new FormData(form);try{await api({action:'create_reel',author:fd.get('author'),handle:fd.get('handle'),title:fd.get('title'),caption:fd.get('caption'),videoUrl:fd.get('videoUrl')});form.reset();form.hidden=true;status.textContent='Published.';await load()}catch(err){status.textContent=err.message}};
section.querySelector('#realVibesPrev').onclick=()=>track.scrollBy({left:-track.clientWidth*.82,behavior:'smooth'});section.querySelector('#realVibesNext').onclick=()=>track.scrollBy({left:track.clientWidth*.82,behavior:'smooth'});load();})();