(()=>{
const TOKEN='hubcore_member_token',USER='hubcore_member',FOUNDER='hubcore-founder-token-v1';
const plans={day:['24-hour Promo Vibe','R10'],three:['3-day Promo Reel','R29'],week:['7-day Promo Reel','R49'],featured:['Featured 7-day Promo','R99']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const user=()=>{try{return JSON.parse(localStorage.getItem(USER)||'null')}catch{return null}};
const token=()=>localStorage.getItem(TOKEN)||'',founder=()=>localStorage.getItem(FOUNDER)||'';
let chosenReel=null,selectedPlan='three';
async function post(body,useFounder=false){const t=useFounder?founder():token(),h={'Content-Type':'application/json'};if(t)h.Authorization='Bearer '+t;const r=await fetch('/api/vibepromote',{method:'POST',headers:h,body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to complete that request.');return d}
function nav(){const n=document.getElementById('primaryNavigation');if(!n||n.querySelector('[href="#vibe-promote"]'))return;const a=document.createElement('a');a.href='#vibe-promote';a.textContent='VibePromote';n.querySelector('[href="#reel-vibes"]')?.insertAdjacentElement('afterend',a)}
function installCss(){if(document.getElementById('vp-css'))return;const l=document.createElement('link');l.id='vp-css';l.rel='stylesheet';l.href='vibepromote.css?v=20260916-income1';document.head.appendChild(l)}
function html(){return `<section id="vibe-promote" class="section reveal"><div class="vp-head"><div><div class="eyebrow">OPT-IN BUSINESS + CREATOR DISCOVERY</div><h2>Meet <span>VibePromote.</span></h2><p>Your normal HubCore feed stays vibe-first. Paid business and creator promotions live here in their own space, only for people who choose to browse them.</p></div><div class="vp-principle"><strong>No advert wall.</strong><span>Promotions never automatically enter Community or the normal Reel Vibes feed.</span></div></div><div class="vp-packages">${Object.entries(plans).map(([k,p])=>`<article class="vp-plan ${k==='featured'?'featured':''}"><span class="vp-plan-badge">${k==='featured'?'Featured':'Beta launch'}</span><h3>${p[0]}</h3><div class="vp-price">${p[1]}</div><p>${k==='day'?'A tiny first boost.':k==='three'?'Three days in VibePromote.':k==='week'?'A full week of discovery.':'Priority placement for seven days.'}</p><button class="btn ${k==='featured'?'primary':'ghost'}" data-plan="${k}" type="button">Choose ${p[1]}</button></article>`).join('')}</div><div class="vp-toolbar"><div><div class="eyebrow">PROMOTIONAL VIBES</div><h3>Discover businesses and creators</h3></div><small>Every item is clearly marked PROMOTED.</small></div><div id="vpFeed" class="vp-feed"></div><div id="vpFounder" class="vp-founder" hidden><div class="vp-founder-head"><h3>Founder · VibePromote approvals</h3><button class="btn ghost" id="vpRefresh" type="button">Refresh</button></div><div id="vpFounderList" class="vp-founder-list"></div></div></section><div class="vp-modal" id="vpModal" hidden><div class="vp-modal-card"><button class="vp-close" type="button">×</button><div class="eyebrow">VIBEPROMOTE</div><h3>Promote this Reel Vibe</h3><p id="vpReelName"></p><form id="vpForm" class="vp-form"><div class="vp-row"><label>Business / creator name<input name="businessName" maxlength="100" required></label><label>Category<select name="category"><option>Business</option><option>Creator</option><option>Gaming</option><option>Music</option><option>Food</option><option>Automotive</option><option>Fashion</option><option>Travel</option><option>Event</option><option>Service</option><option>Other</option></select></label></div><label>Promotion title<input name="title" maxlength="120" required></label><label>Short description<textarea name="description" maxlength="900"></textarea></label><label>Business / booking link <small>Optional · https only</small><input name="destinationUrl" type="url" placeholder="https://..."></label><label>Package<select name="plan">${Object.entries(plans).map(([k,p])=>`<option value="${k}">${p[0]} — ${p[1]}</option>`).join('')}</select></label><div class="vp-submit-line"><button class="btn primary" type="submit">Submit Promotion</button><span id="vpStatus" class="vp-status"></span></div><div id="vpPaymentResult" class="vp-payment-result" hidden></div></form></div></div>`}
function installSection(){if(document.getElementById('vibe-promote'))return;const a=document.getElementById('ai')||document.getElementById('reality');if(!a)return;a.insertAdjacentHTML('beforebegin',html());bind()}
function openPromo(reel,plan=selectedPlan){const u=user();if(!u||!token()){document.getElementById('contact')?.scrollIntoView({behavior:'smooth'});location.hash='contact';return}if(!reel){alert('Upload a Reel Vibe first, then tap Promote on that Reel.');document.getElementById('reel-vibes')?.scrollIntoView({behavior:'smooth'});return}chosenReel=reel;selectedPlan=plans[plan]?plan:'three';const m=document.getElementById('vpModal'),f=document.getElementById('vpForm');f.reset();f.elements.businessName.value=u.name||'';f.elements.title.value=reel.title||'';f.elements.plan.value=selectedPlan;document.getElementById('vpReelName').textContent=`Selected Reel: ${reel.title}`;document.getElementById('vpStatus').textContent='';document.getElementById('vpPaymentResult').hidden=true;m.hidden=false;document.body.style.overflow='hidden'}
function close(){document.getElementById('vpModal').hidden=true;document.body.style.overflow=''}
function media(url,title){return /\.(mp4|webm|mov)(?:$|\?)/i.test(url)?`<video controls playsinline preload="metadata" src="${esc(url)}"></video>`:`<img loading="lazy" src="${esc(url)}" alt="${esc(title)}">`}
function promoCard(p){return `<article class="vp-card ${p.featured?'featured':''}" data-id="${esc(p.id)}"><div class="vp-media">${media(p.mediaUrl,p.title)}<span class="vp-badge">PROMOTED</span>${p.featured?'<span class="vp-badge vp-featured">FEATURED</span>':''}</div><div class="vp-card-body"><span class="vp-category">${esc(p.category)}</span><h3>${esc(p.title)}</h3><div class="vp-business">${esc(p.businessName)}</div><p>${esc(p.description)}</p><div class="vp-stats"><span>👁 ${Number(p.views||0)} views</span><span>↗ ${Number(p.clicks||0)} visits</span></div>${p.destinationUrl?`<div class="vp-card-actions"><a class="btn primary" data-visit href="${esc(p.destinationUrl)}" target="_blank" rel="noopener sponsored">Visit</a></div>`:''}</div></article>`}
async function loadFeed(){const root=document.getElementById('vpFeed');try{const r=await fetch('/api/vibepromote',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);root.innerHTML=d.promotions?.length?d.promotions.map(promoCard).join(''):`<div class="vp-empty"><strong>Be the first VibePromote customer.</strong><p>No paid promotions are live yet.</p></div>`;root.querySelectorAll('[data-visit]').forEach(a=>a.onclick=()=>post({action:'click',id:a.closest('[data-id]').dataset.id}).catch(()=>{}));const seen=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting||e.intersectionRatio<.55)return;const id=e.target.dataset.id,k='vp-view-'+id;if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,'1');post({action:'view',id}).catch(()=>{})}seen.unobserve(e.target)}),{threshold:[.55]});root.querySelectorAll('[data-id]').forEach(x=>seen.observe(x))}catch(e){root.innerHTML=`<div class="vp-empty"><strong>VibePromote is preparing.</strong><p>${esc(e.message)}</p></div>`}}
function adminCard(p){return `<article class="vp-admin-card" data-id="${esc(p.id)}"><div><strong>${esc(p.businessName)} · ${esc(p.title)}</strong><p>${esc(p.contactEmail)} · ${esc(p.planLabel)} · R${Math.round(p.amountCents/100)}</p><div class="vp-admin-meta"><span>Payment: ${esc(p.paymentStatus)}</span><span>Status: ${esc(p.status)}</span></div></div><div class="vp-admin-actions"><button data-act="${p.paymentStatus==='paid'?'mark_unpaid':'mark_paid'}">${p.paymentStatus==='paid'?'Mark unpaid':'Mark paid'}</button><button data-act="approve">Approve</button><button data-act="reject">Reject</button></div></article>`}
async function loadFounder(){if(!founder())return;const panel=document.getElementById('vpFounder'),root=document.getElementById('vpFounderList');panel.hidden=false;try{const r=await fetch('/api/vibepromote?founder=1',{headers:{Authorization:'Bearer '+founder()},cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);root.innerHTML=d.promotions?.length?d.promotions.map(adminCard).join(''):'<div class="vp-admin-empty">No submissions yet.</div>';root.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await post({action:b.dataset.act,id:b.closest('[data-id]').dataset.id},true);await loadFounder();await loadFeed()}catch(e){alert(e.message)}finally{b.disabled=false}})}catch(e){root.innerHTML=`<div class="vp-admin-empty">${esc(e.message)}</div>`}}
function addPromoteButtons(){document.querySelectorAll('#real-vibes .real-vibe-card').forEach(c=>{const s=c.querySelector('.reel-social');if(!s||s.querySelector('[data-promote]'))return;const b=document.createElement('button');b.type='button';b.dataset.promote='1';b.innerHTML='🚀 <b>Promote</b>';b.onclick=()=>openPromo({id:c.dataset.id,title:c.querySelector('h3')?.textContent||'Reel Vibe'},selectedPlan);s.appendChild(b)})}
function bind(){document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{selectedPlan=b.dataset.plan;alert(`${plans[selectedPlan][1]} package selected. Now choose the Reel Vibe you want to promote.`);document.getElementById('reel-vibes')?.scrollIntoView({behavior:'smooth'})});document.querySelector('.vp-close').onclick=close;document.getElementById('vpModal').onclick=e=>{if(e.target.id==='vpModal')close()};document.getElementById('vpRefresh')?.addEventListener('click',loadFounder);document.getElementById('vpForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),s=document.getElementById('vpStatus'),res=document.getElementById('vpPaymentResult'),btn=f.querySelector('button[type="submit"]');if(!chosenReel)return;s.textContent='Submitting…';s.className='vp-status';btn.disabled=true;try{const d=await post({action:'submit',reelId:chosenReel.id,businessName:fd.get('businessName'),category:fd.get('category'),title:fd.get('title'),description:fd.get('description'),destinationUrl:fd.get('destinationUrl'),plan:fd.get('plan')});s.textContent='Promotion submitted.';s.className='vp-status success';res.hidden=false;res.innerHTML=d.paymentConfigured?`<strong>${esc(d.plan.label)} · R${Math.round(d.plan.amountCents/100)}</strong><p>Reference: ${esc(d.reference)}. Complete payment below. Your campaign starts only after payment is confirmed and HubCore approves it.</p><a class="btn primary" href="${esc(d.paymentUrl)}" target="_blank" rel="noopener">Pay now</a>`:`<strong>${esc(d.plan.label)} · R${Math.round(d.plan.amountCents/100)}</strong><p>Reference: ${esc(d.reference)}. Your request is saved. HubCore has been notified by email and will contact the email on your account to arrange payment.</p>`;if(founder())loadFounder()}catch(err){s.textContent=err.message;s.className='vp-status error'}finally{btn.disabled=false}};loadFeed();loadFounder();addPromoteButtons();const r=document.getElementById('reel-vibes');if(r)new MutationObserver(addPromoteButtons).observe(r,{subtree:true,childList:true})}
function init(){installCss();nav();installSection()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
