function json(data,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8'}})}
const clean=(v,n=300)=>String(v??'').trim().slice(0,n);
const enc=new TextEncoder();
async function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:150000,hash:'SHA-256'},key,256))}
async function digest(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function ensure(db){await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS hubcore_users (id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,profile_photo TEXT NOT NULL DEFAULT '')`),
 db.prepare(`CREATE TABLE IF NOT EXISTS hubcore_sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES hubcore_users(id) ON DELETE CASCADE)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_hubcore_sessions_user ON hubcore_sessions(user_id,expires_at DESC)`)
])}
async function notify(env,u){if(!env?.RESEND_API_KEY||!env?.CONTACT_FROM_EMAIL)return false;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.CONTACT_FROM_EMAIL,to:['hubcore-vibes@outlook.com'],reply_to:u.email,subject:`NEW HUBCORE SIGNUP — @${u.username}`,text:`New HubCore Vibes member\n\nName: ${u.name}\nUsername: @${u.username}\nEmail: ${u.email}`})});return r.ok}
async function sessionUser(request,db){const auth=request.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return null;const th=await digest(auth.slice(7));return db.prepare(`SELECT u.id,u.name,u.email,u.username,u.profile_photo FROM hubcore_sessions s JOIN hubcore_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(th,Date.now()).first()}
export async function onRequestGet({request,env}){if(!env?.DB)return json({error:'Account database unavailable.'},503);try{await ensure(env.DB);const u=await sessionUser(request,env.DB);return u?json({user:{...u,profilePhoto:u.profile_photo}}):json({error:'Please log in.'},401)}catch{return json({error:'Unable to load account.'},500)}}
export async function onRequestPost({request,env}){if(!env?.DB)return json({error:'Account database unavailable.'},503);try{await ensure(env.DB);const b=await request.json(),action=clean(b.action,20);
 if(action==='signup'){const name=clean(b.name,80),email=clean(b.email,200).toLowerCase(),username=clean(b.username,40).replace(/^@+/,'').replace(/[^a-zA-Z0-9_.]/g,''),password=String(b.password||'');if(!name||!email||username.length<3||password.length<8)return json({error:'Enter your name, valid email, username and a password of at least 8 characters.'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:'Enter a valid email address.'},400);const taken=await env.DB.prepare('SELECT id FROM hubcore_users WHERE email=? OR username=?').bind(email,username).first();if(taken)return json({error:'That email or username is already registered.'},409);const id=crypto.randomUUID(),salt=crypto.randomUUID(),ph=await hashPassword(password,salt),now=Date.now();await env.DB.prepare(`INSERT INTO hubcore_users(id,created_at,name,email,username,password_hash,password_salt) VALUES(?,?,?,?,?,?,?)`).bind(id,now,name,email,username,ph,salt).run();const token=crypto.randomUUID()+crypto.randomUUID(),th=await digest(token);await env.DB.prepare('INSERT INTO hubcore_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(th,id,now+2592000000,now).run();let notificationSent=false;try{notificationSent=await notify(env,{name,email,username})}catch{}return json({ok:true,token,user:{id,name,email,username,profilePhoto:''},notificationSent},201)}
 if(action==='login'){const login=clean(b.login,200).replace(/^@/,'').toLowerCase(),password=String(b.password||''),u=await env.DB.prepare('SELECT * FROM hubcore_users WHERE lower(email)=? OR lower(username)=?').bind(login,login).first();if(!u||await hashPassword(password,u.password_salt)!==u.password_hash)return json({error:'Incorrect email, username or password.'},401);const token=crypto.randomUUID()+crypto.randomUUID(),th=await digest(token),now=Date.now();await env.DB.prepare('INSERT INTO hubcore_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(th,u.id,now+2592000000,now).run();return json({ok:true,token,user:{id:u.id,name:u.name,email:u.email,username:u.username,profilePhoto:u.profile_photo}})}
 if(action==='logout'){const auth=request.headers.get('Authorization')||'';if(auth.startsWith('Bearer '))await env.DB.prepare('DELETE FROM hubcore_sessions WHERE token_hash=?').bind(await digest(auth.slice(7))).run();return json({ok:true})}
 return json({error:'Unknown account action.'},400)
}catch(e){return json({error:'Unable to process account request.'},500)}}