function json(data,status=200,headers={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store, no-cache, must-revalidate','Content-Type':'application/json; charset=utf-8',...headers}});}
const clean=(v,max)=>String(v??'').trim().slice(0,max);
const enc=new TextEncoder();
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function randomHex(bytes=24){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:120000,hash:'SHA-256'},key,256);return bytesToHex(bits);}
async function ensure(db){
  await db.prepare(`CREATE TABLE IF NOT EXISTS early_access_signups (id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,username TEXT NOT NULL,note TEXT,status TEXT NOT NULL DEFAULT 'pending')`).run();
  const info=await db.prepare('PRAGMA table_info(early_access_signups)').all();const cols=new Set((info.results||[]).map(r=>r.name));
  const adds=[['password_salt','TEXT'],['password_hash','TEXT'],['approval_token','TEXT'],['approved_at','INTEGER'],['last_login_at','INTEGER']];
  for(const [name,type] of adds){if(!cols.has(name))await db.prepare(`ALTER TABLE early_access_signups ADD COLUMN ${name} ${type}`).run();}
  await db.prepare(`CREATE TABLE IF NOT EXISTS early_access_sessions (token TEXT PRIMARY KEY,signup_id TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,FOREIGN KEY(signup_id) REFERENCES early_access_signups(id) ON DELETE CASCADE)`).run();
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_early_access_email ON early_access_signups(email)').run();
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_early_access_username ON early_access_signups(username)').run();
  await db.prepare('CREATE INDEX IF NOT EXISTS idx_early_access_sessions_expiry ON early_access_sessions(expires_at)').run();
}
function cookieToken(request){const raw=request.headers.get('Cookie')||'';const m=raw.match(/(?:^|;\s*)hubcore_early_session=([^;]+)/);return m?decodeURIComponent(m[1]):'';}
function sessionCookie(token,maxAge=604800){return `hubcore_early_session=${encodeURIComponent(token)}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;}
function emailConfig(env){return {apiKey:env?.RESEND_API_KEY,to:env?.CONTACT_NOTIFICATION_EMAIL||env?.INVESTOR_NOTIFICATION_EMAIL,from:env?.CONTACT_FROM_EMAIL||env?.INVESTOR_FROM_EMAIL};}
async function sendEmail(env,payload){const {apiKey,from}=emailConfig(env);if(!apiKey||!from)return false;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from,...payload})});return r.ok;}
async function notifyFounder(env,request,lead){const {to}=emailConfig(env);if(!to)return false;const origin=new URL(request.url).origin;const approve=`${origin}/api/early-access?approve=${encodeURIComponent(lead.approvalToken)}`;return sendEmail(env,{to:[to],reply_to:lead.email,subject:`Approve HubCore Vibes early access — ${lead.username}`,text:[`New early access application`,``,`Name: ${lead.name}`,`Email: ${lead.email}`,`Username: ${lead.username}`,`Message: ${lead.note||'-'}`,``,`APPROVE THIS PERSON:`,approve,``,`Only approve people you want to give early access.`].join('\n')});}
async function notifyApplicantApproved(env,lead,origin){return sendEmail(env,{to:[lead.email],subject:'Your HubCore Vibes early access has been approved',text:[`Hi ${lead.name},`,``,`Your HubCore Vibes early access has been approved.`,`You can now sign in using the email address and password you chose when you applied.`,``,`Sign in: ${origin}/#contact`,``,`Welcome to the journey ahead.`,`HubCore Vibes`].join('\n')});}
function approvalPage(title,message,ok=true){return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{margin:0;background:#080611;color:#f7f1ff;font-family:Inter,Arial,sans-serif;display:grid;place-items:center;min-height:100vh;padding:24px}.card{max-width:620px;padding:34px;border:1px solid #6f45aa;border-radius:24px;background:#120b20;box-shadow:0 20px 60px #0008}h1{margin-top:0}.ok{color:#b98cff}.bad{color:#ff9b9b}a{display:inline-block;margin-top:18px;padding:12px 18px;border-radius:999px;background:#8f4dff;color:white;text-decoration:none;font-weight:700}</style></head><body><div class="card"><h1 class="${ok?'ok':'bad'}">${title}</h1><p>${message}</p><a href="/#contact">Open HubCore Vibes</a></div></body></html>`,{status:ok?200:400,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});}
export async function onRequestGet({request,env}){
  if(!env?.DB)return json({error:'Early access database is not connected.'},503);
  try{await ensure(env.DB);const url=new URL(request.url),approval=clean(url.searchParams.get('approve'),200);
    if(approval){const lead=await env.DB.prepare('SELECT id,name,email,username,status FROM early_access_signups WHERE approval_token=?').bind(approval).first();if(!lead)return approvalPage('Approval link not found','This approval link is invalid or has already expired.',false);if(lead.status==='approved')return approvalPage('Already approved',`${lead.name} already has HubCore Vibes early access.`);await env.DB.prepare(`UPDATE early_access_signups SET status='approved',approved_at=?,approval_token=NULL WHERE id=?`).bind(Date.now(),lead.id).run();let sent=false;try{sent=await notifyApplicantApproved(env,lead,url.origin);}catch{}return approvalPage('Early access approved',`${lead.name} (${lead.username}) can now sign in.${sent?' An approval email was sent to them.':' Their account is active now.'}`);}
    const token=cookieToken(request);if(!token)return json({loggedIn:false});await env.DB.prepare('DELETE FROM early_access_sessions WHERE expires_at < ?').bind(Date.now()).run();const row=await env.DB.prepare(`SELECT s.name,s.email,s.username,s.status,s.approved_at FROM early_access_sessions x JOIN early_access_signups s ON s.id=x.signup_id WHERE x.token=? AND x.expires_at>?`).bind(token,Date.now()).first();if(!row||row.status!=='approved')return json({loggedIn:false});return json({loggedIn:true,profile:{name:row.name,email:row.email,username:row.username,status:row.status,approvedAt:row.approved_at}});
  }catch(error){return json({error:'Unable to check early access right now.'},500);}
}
export async function onRequestPost({request,env}){
  if(!env?.DB)return json({error:'Early access database is not connected.'},503);
  try{await ensure(env.DB);const body=await request.json(),action=clean(body.action||'apply',30);
    if(action==='apply'){
      const lead={name:clean(body.name,120),email:clean(body.email,200).toLowerCase(),username:clean(body.username,40).replace(/\s+/g,''),password:String(body.password||''),note:clean(body.note,500)};
      if(!lead.name||!lead.email||!lead.username||!lead.password)return json({error:'Name, email, username and password are required.'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(lead.email))return json({error:'Please enter a valid email address.'},400);if(lead.password.length<8)return json({error:'Choose a password with at least 8 characters.'},400);lead.username='@'+lead.username.replace(/^@+/,'');
      const existing=await env.DB.prepare('SELECT id,status FROM early_access_signups WHERE email=? OR username=? LIMIT 1').bind(lead.email,lead.username).first();if(existing?.status==='approved')return json({error:'This email or username already has early access. Please sign in.'},409);
      const salt=randomHex(16),hash=await passwordHash(lead.password,salt),approvalToken=randomHex(32),now=Date.now();let id=existing?.id||crypto.randomUUID();
      if(existing){await env.DB.prepare(`UPDATE early_access_signups SET created_at=?,name=?,email=?,username=?,note=?,status='pending',password_salt=?,password_hash=?,approval_token=?,approved_at=NULL WHERE id=?`).bind(now,lead.name,lead.email,lead.username,lead.note||null,salt,hash,approvalToken,id).run();}
      else{await env.DB.prepare(`INSERT INTO early_access_signups (id,created_at,name,email,username,note,status,password_salt,password_hash,approval_token) VALUES (?,?,?,?,?,?,'pending',?,?,?)`).bind(id,now,lead.name,lead.email,lead.username,lead.note||null,salt,hash,approvalToken).run();}
      let notificationSent=false;try{notificationSent=await notifyFounder(env,request,{...lead,approvalToken});}catch{}return json({ok:true,id,status:'pending',notificationSent,message:notificationSent?'Application received. The founder has been emailed an approval link.':'Application received and saved. Email notification is not configured yet.'},201);
    }
    if(action==='login'){
      const email=clean(body.email,200).toLowerCase(),password=String(body.password||'');if(!email||!password)return json({error:'Email and password are required.'},400);const lead=await env.DB.prepare('SELECT id,name,email,username,status,password_salt,password_hash FROM early_access_signups WHERE email=? LIMIT 1').bind(email).first();if(!lead)return json({error:'No early access application was found for this email.'},404);if(lead.status!=='approved')return json({error:'Your application is still waiting for founder approval.'},403);if(!lead.password_salt||!lead.password_hash)return json({error:'This account needs to re-apply to set a secure password.'},409);const actual=await passwordHash(password,lead.password_salt);if(actual!==lead.password_hash)return json({error:'Incorrect password.'},401);const token=randomHex(32),now=Date.now(),expires=now+7*24*60*60*1000;await env.DB.prepare('INSERT INTO early_access_sessions (token,signup_id,created_at,expires_at) VALUES (?,?,?,?)').bind(token,lead.id,now,expires).run();await env.DB.prepare('UPDATE early_access_signups SET last_login_at=? WHERE id=?').bind(now,lead.id).run();return json({ok:true,profile:{name:lead.name,email:lead.email,username:lead.username,status:'approved'}},200,{'Set-Cookie':sessionCookie(token)});
    }
    if(action==='logout'){
      const token=cookieToken(request);if(token)await env.DB.prepare('DELETE FROM early_access_sessions WHERE token=?').bind(token).run();return json({ok:true},200,{'Set-Cookie':sessionCookie('',0)});
    }
    return json({error:'Unknown early access action.'},400);
  }catch(error){return json({error:'Unable to process early access right now.'},500);}
}
