function json(data,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8'}})}
const enc=new TextEncoder();async function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}async function digest(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function user(request,db){const a=request.headers.get('Authorization')||'';if(!a.startsWith('Bearer '))return null;return db.prepare(`SELECT u.id,u.username FROM hubcore_sessions s JOIN hubcore_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(await digest(a.slice(7)),Date.now()).first()}
const imageTypes=new Set(['image/jpeg','image/png','image/webp','image/gif']);const videoTypes=new Set(['video/mp4','video/webm','video/quicktime']);
async function dataUrl(file){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return `data:${file.type};base64,${btoa(binary)}`}
export async function onRequestPost({request,env}){if(!env?.DB)return json({error:'Account database unavailable.'},503);try{const u=await user(request,env.DB);if(!u)return json({error:'Please sign up or log in first.'},401);const form=await request.formData(),file=form.get('file'),kind=String(form.get('kind')||'');if(!(file instanceof File)||!file.size)return json({error:'Choose a file to upload.'},400);
 if(kind==='profile'){if(!imageTypes.has(file.type)||file.size>750000)return json({error:'Profile photo must be JPG, PNG, WebP or GIF and under 750 KB.'},400);const data=await dataUrl(file);await env.DB.prepare('UPDATE hubcore_users SET profile_photo=? WHERE id=?').bind(data,u.id).run();return json({ok:true,url:data})}
 if(kind==='reel-image'){if(!imageTypes.has(file.type))return json({error:'Photo Reels support JPG, PNG, WebP and GIF images.'},400);if(file.size>4*1024*1024)return json({error:'Keep your photo under 4 MB.'},413);if(env?.MEDIA){const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':file.type==='image/gif'?'gif':'jpg',key=`reels/${u.id}/${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{owner:u.id,username:u.username,kind:'reel-image'}});return json({ok:true,url:`/api/media/${key}`,mediaType:'image'})}if(file.size>950000)return json({error:'Photo storage is available now, but without the media bucket photos must be under 950 KB. HubCore will compress photos before upload.'},413);return json({ok:true,url:await dataUrl(file),mediaType:'image',fallbackStorage:true})}
 if(kind==='reel'){if(!videoTypes.has(file.type))return json({error:'Video Reels support MP4, WebM and MOV files.'},400);if(file.size>100*1024*1024)return json({error:'Keep your reel under 100 MB.'},413);if(!env?.MEDIA)return json({error:'Video storage still needs the Cloudflare MEDIA bucket. Photo Reel uploads are available now.'},503);const ext=file.type==='video/mp4'?'mp4':file.type==='video/webm'?'webm':'mov',key=`reels/${u.id}/${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{owner:u.id,username:u.username,kind:'reel-video'}});return json({ok:true,url:`/api/media/${key}`,mediaType:'video'})}
 return json({error:'Unknown upload type.'},400)
}catch(e){console.error('HubCore upload error',e);return json({error:'Unable to upload this file.'},500)}}